image: circleci/elixir:1.10.4-node-browsers
services:
  - postgres:12.2-alpine
variables:
  DATABASE_URL: postgresql://postgres:@$POSTGRES_HOST:5432/$POSTGRES_DB
  POSTGRES_DB: epicenter_test
  POSTGRES_HOST: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: ""
  POSTGRES_USER: postgres
cache:
  key:
    files:
      - mix.lock
      - assets/package-lock.json
    prefix: v1
  paths:
    - deps
    - assets/node_modules
before_script:
  - sudo apt install ssh-askpass
  - mkdir -p ~/.ssh && chmod 0700 ~/.ssh
  - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - npm install --prefix assets
  - mix local.rebar --force
  - mix local.hex --force
  - mix hex.organization auth geometer --key "$HEX_GEOMETER_READ_ONLY_KEY"
  - mix deps.get --only test
test:
  script:
    - bin/dev/test
