image: circleci/elixir:1.10.4-node-browsers
services:
  - postgres:12.2-alpine
variables:
  POSTGRES_DB: epicenter_test
  POSTGRES_HOST: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
cache:
  key:
    files:
      - mix.lock
      - assets/package-lock.json
    prefix: v1
  paths:
    - deps
    - assets/node_modules
before_script:
  - npm install --prefix assets
  - mix local.rebar --force
  - mix local.hex --force
  - mix hex.organization auth geometer --key "$HEX_GEOMETER_READ_ONLY_KEY"
  - mix deps.get
  - mix deps.audit
test:
  script:
    - bin/dev/test
