version: "3.7"
services:
  postgres:
    image: postgres:12.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: epicenter_dev
    ports:
      - 5433:5432
  runner:
    image: epicenter:latest
    ports:
      - 4001:4000
    volumes:
      - ./tmp/ssl:/opt/ssl:ro
    environment:
      ALLOW_PRIVATE_WEB: "true"
      CANONICAL_HOST: viewpoint-dev.network.ratiopbc.dev
      DATABASE_URL: ecto://postgres:postgres@postgres:5432/epicenter_dev
      DBSSL: "false"
      ERROR_REPORTER_SERVICE_NAME: viewpoint-dev
      LIVE_VIEW_SIGNING_SALT: xbK8/I1ibfroHQvkZTMKbO7NOLAHtbdP
      RELEASE_LEVEL: dev
      SECRET_KEY_BASE: 3TjNgvbwkybwa/wmAHz6kgakyAZ5ETIBCGuKRFW1s/ebkOqElLgtQrJrPZqY51cr
    depends_on:
      - postgres
