use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :epicenter, EpicenterWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  url: [host: {:system, "CANONICAL_HOST"}, port: 443, scheme: "https"]

config :epicenter,
  user_input_restrictions: :unrestricted

config :logger,
  level: :info,
  backends: [LoggerJSON]

config :logger_json, :backend,
  # don't change this! ensures we get all the metadata, including audit logs
  metadata: :all,
  formatter: LoggerJSON.Formatters.GoogleCloudLogger

# prevents duplicate ecto logs (LoggerJSON configured in application.ex start/2)
config :epicenter, Epicenter.Repo,
  adapter: Ecto.Adapters.Postgres,
  log: false
