use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :epicenter, EpicenterWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: {:system, "CANONICAL_HOST"}, port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]]

config :epicenter,
  application_version_sha: System.get_env("SOURCE_VERSION"),
  user_input_restrictions: :unrestricted

config :logger,
  level: :info,
  backends: [LoggerJSON]

config :logger_json, :backend,
  # don't change this! ensures we get all the metadata, including audit logs
  metadata: :all,
  formatter: LoggerJSON.Formatters.GoogleCloudLogger

# prevents duplicate ecto logs (LoggerJSON configured in application.ex start/2)
config :epicenter, Epicenter.Repo,
  adapter: Ecto.Adapters.Postgres,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: System.get_env("DBSSL", "true") == "true",
  url: System.get_env("DATABASE_URL"),
  log: false
