name: CI

on:
  push:
    branches: [ gh-actions ]

env:
  POSTGRES_DB: epicenter_test
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
    
jobs:
#   test:
#     runs-on: ubuntu-latest
    
#     env:
#       MIX_ENV: test

#     services:
#       postgres:
#         image: postgres:12.5-alpine
#         env:
#           POSTGRES_PASSWORD: postgres
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#         ports:
#           - 5432:5432

#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-elixir@v1
#         with:
#           otp-version: '23.2.2'
#           elixir-version: '1.11.3'

#       - name: Install dependencies
#         run: |
#           npm install --prefix assets
#           mix local.rebar --force
#           mix local.hex --force
#           mix deps.get
#           mix deps.unlock --check-unused
#           mix deps.audit
#           npm audit --audit-level=moderate --prefix assets
#           mix sobelow --config
      
#       - name: Run tests
#         run: bin/dev/test
#         env: 
#           POSTGRES_HOST: localhost
#           POSTGRES_PORT: 5432
  
#   # TODO: this needs a new container registry to store/retrieve images
#   build_image:
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
      
#       - name: Build image
#         run: bin/docker/build
  
  deploy_heroku:
    runs-on: ubuntu-latest
    
#     needs: test
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: AkhileshNS/heroku-deploy@v3.11.10
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: $HEROKU_API_KEY
          # Email that you use with heroku
          heroku_app_name: $HEROKU_APP_STAGING
      
#       - name: Deploy to Heroku
#         run: |
#           git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_STAGING.git || true
#           git push -f heroku HEAD:master
