name: CI

on:
  push:
    branches: [ gh-actions ]

env:
  GITLAB_CI: true
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  POSTGRES_DB: epicenter_test
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
    
jobs:
#   test:
#     runs-on: ubuntu-latest
    
#     env:
#       MIX_ENV: test

#     services:
#       postgres:
#         image: postgres:12.5-alpine
#         env:
#           POSTGRES_PASSWORD: postgres
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#         ports:
#           - 5432:5432

#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-elixir@v1
#         with:
#           otp-version: '23.2.2'
#           elixir-version: '1.11.3'

#       - name: Install dependencies
#         run: |
#           npm install --prefix assets
#           mix local.rebar --force
#           mix local.hex --force
#           mix deps.get
#           mix deps.unlock --check-unused
#           mix deps.audit
#           npm audit --audit-level=moderate --prefix assets
#           mix sobelow --config
      
#       - name: Run tests
#         run: bin/dev/test
#         env: 
#           POSTGRES_HOST: localhost
#           POSTGRES_PORT: 5432
  
  build_image:
    runs-on: ubuntu-latest
    
    steps:
      - uses: docker/build-push-action@v2.3.0
        with:
          target: geometer/docker-gcp:latest
      
      - name: Build image
        run: bin/docker/build
