name: CI

on:
  push:
    branches: [ gh-actions ]

env:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  POSTGRES_DB: epicenter_test
  POSTGRES_HOST: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
    
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.5-alpine
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MIX_ENV: test
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23.2.2'
          elixir-version: '1.11.3'

      - name: Install dependencies
        run: |
          npm install --prefix assets
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.unlock --check-unused
          mix deps.audit
          npm audit --audit-level=moderate --prefix assets
          mix sobelow --config
      
      - name: Run tests
        run: bin/dev/test
